
name: CI/CD pipline

on:
  push:
    branches: [  "feature"  ]
  pull_request:
    branches: [ "main"  ]

jobs:
  test: 
    runs-on: ubuntu-latest
    steps: 
      - name: Running tests
        run: echo "------------Running unit tests...------------"
      - name: Test Results   
        run: echo "------------The tests have been successfully passed! ------------"

  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t kurs . 
      - name: Deploy the Docker image
        run: | 
              docker stop kurs
              docker rm kurs
              docker run --name kurs -d -p 127.0.0.2:80:80 docker.io/library/kurs
